# Nome da nossa automação
name: CI - Backend Nest.js

# Quando ela deve rodar? 
on:
  push:
    branches: [ main ] # Quando houver push nestas branches
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Quando um PR for aberto para a main
env:
  # Variáveis de ambiente necessárias para os testes
  
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  SERVICE_NAME: automacao-de-pr-com-ia

  # ------------------------------------------------------------
# JOB 1: Testes e Validação do Código
# ------------------------------------------------------------
jobs:
  build-and-test:
    # O "computador" que o GitHub vai nos emprestar (Linux)
    runs-on: ubuntu-latest

    steps:
      # 1. Copia o código do seu repositório para a máquina do GitHub
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 2. Instala o Node.js na versão correta
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Agiliza as próximas rodadas salvando o cache do npm

      # 3. Instala as dependências (Equivalente ao seu npm install)
      - name: Instalar Dependências
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      # 4. Compila o código TypeScript
      - name: Compilar Código
        run: npm run build

      # 5. Verifica o Lint (Padronização de código)
      - name: Rodar Lint
        run: npm run lint

      # 6. Executa os Testes Unitários
      # Se um teste falhar, o deploy nem acontece!
      - name: Rodar Testes
        run: npm run test
        
  # ------------------------------------------------------------
  # JOB 2: Forçar o Deploy Imediato no Railway
  # ------------------------------------------------------------
  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-and-test # SÓ RODA SE OS TESTES PASSAREM!
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Trigger Railway Deploy
        # Substitua 'automacao-de-pr-com-ia' se o nome do seu serviço no Railway for diferente
        run: railway up --service ${{ env.SERVICE_NAME }} --detach
        env:
          RAILWAY_TOKEN: ${{ env.RAILWAY_TOKEN }}
  





